"""Add payment status to booking

Revision ID: 1df1ee390495
Revises: 916caf2de4e4
Create Date: 2025-01-07 23:32:49.850980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df1ee390495'
down_revision = '916caf2de4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Enum('Due', 'Paid', name='paymentstatus'), nullable=False, server_default='Due'))


    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('lng',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('lng',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('payment_status')


    # ### end Alembic commands ###
