"""Add lat and lng columns to Location model

Revision ID: 916caf2de4e4
Revises: 0c6aab87f50f
Create Date: 2025-01-07 05:32:06.140509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916caf2de4e4'
down_revision = '0c6aab87f50f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float, nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float, nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
